### ISSUE TITLE
Python error upon adding mesh

### ISSUE THREAD

**Issue by kingcactuar** [camilosw/board-game-insert#1]
Hi! First off: love the plugin and cannot wait to make stuff with it!

However, I receive the following error when using Add > Mesh > Boardgame Insert > Container:
<img width="787" alt="Screenshot 2024-10-27 at 3 29 43 PM" src="https://github.com/user-attachments/assets/9fc5fd60-656c-454d-89d4-2ef00a0df9f0">

**Configuration:**
Blender version: 4.2.2 LTS RC
Plugin version: 1.2.0
OS: macOS 14.6.1 (23G93)

**Notes:**
- Happens on 2 different macOS computers with the same plugin & Blender version. 
- **Does not occur** when using Add > Mesh > Game Box, Grid Container, or Card Holder. 

Thanks,
C

Full error text:
```
Python: Traceback (most recent call last) :
File "/Users/crdz/Library/Application Support/Blender/4.2/scripts/addons/board_game_insert/bi_operator_classes.py", line 65, in execute create_node(BGI_Node.CONTAINER)
File "/Users/crdz/Library/Application Support/Blender/4.2/scripts/addons/board_game_insert/node_factory.py"
', line 27, in create_node
node_group = bgi_container_create)
^^^^^^^^^^^^^
File "/Users/crdz/Library/Application Support/Blender/4.2/scripts/addons/board_game_insert/bgi_container.py", line 1268, in gi_container_create
bgi_sides = bgi_sides_node_group (bgi_divisor)
^^^^^^^^^^^^^
TypeError: bgi_sides_node_group () takes 0 positional arguments but 1 was given
```

**Comment by camilosw** [comment]
Thanks for reporting. I'll check soon.

**Comment by camilosw** [comment]
@kingcactuar fixed 

https://github.com/camilosw/board-game-insert/releases/tag/1.2.1
